### ISSUE TITLE
Just Enough Research Link

### ISSUE THREAD

**Issue by whitingx** [freshtilledsoil/aux-curriculum#2]
The link to _Erika Hall's_ **'Just Enough Research'** - https://www.dropbox.com/s/op7vjx5sum1arbd/just-enough-research.pdf?dl=0 - on this section - https://github.com/freshtilledsoil/aux-curriculum/blob/master/ux-1-user-research-and-interviewing.md - of the curriculum currently goes to a Dropbox `404` page.

Also, looking at the link it seems to be to a direct download of the copyrighted `PDF` which seems like it could cause problems - might be better to link to the books product page - https://abookapart.com/products/just-enough-research - here instead?

**Comment by joshua-wtc** [comment]
Hey Whitingx, might you have a digital copy of Erika Hall's Just Enough Research?

**Comment by javasteve99** [comment]
Leaving a comment bc I'm at work and don't have time to fix this right now. I was must made aware of this:

Hi there. I'm a former employee of FTS and the original creator of this repo. That link seems to have accidentally survived when this project was internal-only and linked to a lot of copyrighted material that we had legally purchased for the team.

This should absolutely be a link to the product page instead, I must have missed it when I did my original conversion for publication. I'll try to open a pull request tonight to fix it.

@joshua-wtc Please don't request copies of copyrighted material on this repo. It's illegal and unethical. Erika Hall's book is excellent, I highly recommend purchasing a copy. I promise it's worth it.

**Comment by javasteve99** [comment]
Pull request: https://github.com/freshtilledsoil/aux-curriculum/pull/3

Apparently I don't have permissions to accept it. /shrug

**Comment by joshua-wtc** [comment]
@javasteve99 OK Steve, fair enough. Sorry about this.
